import { AppThemeId, ThemeConfig } from '../types';

export const STUDYVERSE_THEMES: Record<AppThemeId, ThemeConfig> = {
  'ocean-blue': {
    id: 'ocean-blue',
    name: 'Ocean Blue',
    category: 'light',
    description: 'Refreshing coastal blue palette with lighthouse & sea wave scenery.',
    primaryColor: '#2563EB',
    primaryHover: '#1D4ED8',
    accentColor: '#38BDF8',
    badgeText: 'Calm & Focused',
    bgHex: '#F0F7FF',
    cardBgHex: '#FFFFFF',
    previewColors: ['#2563EB', '#38BDF8', '#EFF6FF', '#0F172A'],
    colors: {
      primary: '#2563EB',
      primaryHover: '#1D4ED8',
      accent: '#38BDF8',
      bgCanvas: '#F0F7FF',
      cardSurface: '#FFFFFF',
    },
  },
  'midnight-purple': {
    id: 'midnight-purple',
    name: 'Midnight Purple',
    category: 'dark',
    description: 'Deep celestial violet-indigo canvas with glowing nebula moon & constellation scenery.',
    primaryColor: '#A78BFA',
    primaryHover: '#8B5CF6',
    accentColor: '#C084FC',
    badgeText: 'Cosmic Twilight',
    bgHex: '#18152E',
    cardBgHex: '#252048',
    previewColors: ['#A78BFA', '#C084FC', '#18152E', '#F8FAFC'],
    colors: {
      primary: '#A78BFA',
      primaryHover: '#8B5CF6',
      accent: '#C084FC',
      bgCanvas: '#18152E',
      cardSurface: '#252048',
    },
  },
  'forest-green': {
    id: 'forest-green',
    name: 'Forest Green',
    category: 'light',
    description: 'Organic emerald & pine green tones with misty mountain scenery.',
    primaryColor: '#059669',
    primaryHover: '#047857',
    accentColor: '#34D399',
    badgeText: 'Serene Productivity',
    bgHex: '#F0FDF4',
    cardBgHex: '#FFFFFF',
    previewColors: ['#059669', '#34D399', '#F0FDF4', '#0F172A'],
    colors: {
      primary: '#059669',
      primaryHover: '#047857',
      accent: '#34D399',
      bgCanvas: '#F0FDF4',
      cardSurface: '#FFFFFF',
    },
  },
  'sunset-orange': {
    id: 'sunset-orange',
    name: 'Sunset Orange',
    category: 'light',
    description: 'Warm energizing amber & golden sun gradient over layered mountain ridges.',
    primaryColor: '#EA580C',
    primaryHover: '#C2410C',
    accentColor: '#F59E0B',
    badgeText: 'High Energy & Drive',
    bgHex: '#FFF7ED',
    cardBgHex: '#FFFFFF',
    previewColors: ['#EA580C', '#F59E0B', '#FFF7ED', '#0F172A'],
    colors: {
      primary: '#EA580C',
      primaryHover: '#C2410C',
      accent: '#F59E0B',
      bgCanvas: '#FFF7ED',
      cardSurface: '#FFFFFF',
    },
  },
  'minimal-white': {
    id: 'minimal-white',
    name: 'Minimal White',
    category: 'light',
    description: 'Pure distraction-free monochrome slate with modern desk lamp artwork.',
    primaryColor: '#0284C7',
    primaryHover: '#0369A1',
    accentColor: '#64748B',
    badgeText: 'Distraction-Free',
    bgHex: '#FAFAFA',
    cardBgHex: '#FFFFFF',
    previewColors: ['#0284C7', '#64748B', '#FAFAFA', '#0F172A'],
    colors: {
      primary: '#0284C7',
      primaryHover: '#0369A1',
      accent: '#64748B',
      bgCanvas: '#FAFAFA',
      cardSurface: '#FFFFFF',
    },
  },
  'neon-dark': {
    id: 'neon-dark',
    name: 'Neon Dark',
    category: 'dark',
    description: 'High-tech deep slate & cyber navy canvas with glowing emerald & cyan battlestation artwork.',
    primaryColor: '#10B981',
    primaryHover: '#059669',
    accentColor: '#38BDF8',
    badgeText: 'Cyber Slate',
    bgHex: '#0E1A2C',
    cardBgHex: '#182740',
    previewColors: ['#10B981', '#38BDF8', '#0E1A2C', '#F8FAFC'],
    colors: {
      primary: '#10B981',
      primaryHover: '#059669',
      accent: '#38BDF8',
      bgCanvas: '#0E1A2C',
      cardSurface: '#182740',
    },
  },
};

export const THEME_LIST: ThemeConfig[] = Object.values(STUDYVERSE_THEMES);
